# Generated by Django 2.1.4 on 2018-12-12 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('AB', 'Aberto'), ('AT', 'Em Atendimento'), ('NF', 'Negócio Fechado'), ('NR', 'Negócio não Realizado')], max_length=50)),
                ('data', models.DateField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, help_text='500 caracteres no máximo', max_length=500, null=True, verbose_name='Observações')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, help_text='dd/mm/aaa', verbose_name='Data')),
                ('observacoes', models.TextField(blank=True, help_text='500 caracteres no máximo', max_length=500, null=True, verbose_name='Observações')),
                ('atendimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.Atendimento')),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.Pessoa'),
        ),
    ]
